# External component configuration
external_components:
  - source:
      type: local
      path: ../components  # Path relative to this YAML file
    components: [ geappliances_bridge ]

# external_components:
#   - source: github://eddietheengineer/home-assistant-bridge-esphome@develop
#     components: [ geappliances_bridge ]
#     refresh: 1min

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 13dB

api:
  encryption:
    key: !secret api_encryption_key

# Enable logging
logger:
  baud_rate: 0

# Allow OTA updates
ota:
  - platform: esphome

debug:
  update_interval: 1min

sensor:
  - platform: uptime
    type: seconds
    name: Uptime Sensor

  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    min_free:
      name: "Heap Min Free"
    fragmentation:
      name: "Heap Fragmentation"
    loop_time:
      name: "Loop Time"
    cpu_frequency:
      name: "CPU Frequency"

# MQTT configuration for Home Assistant
mqtt:
  broker: !secret mqtt_broker  # Your MQTT broker IP
  username: !secret mqtt_username
  password: !secret mqtt_password
  port: 1883
  discovery: true
  discovery_prefix: homeassistant
  clean_session: true

