/*!
 * @file
 * @brief Erd lists for various appliances
 * 
 * This file is auto-generated from appliance_api_erd_definitions.json
 * Do not edit this file manually. Run scripts/generate_erd_lists.py to regenerate.
 */

#ifndef ERD_LISTS_H
#define ERD_LISTS_H

#include "tiny_erd.h"

// Maximum number of ERDs that can be held in the polling list.
// Sized for the worst case: common ERDs + energy ERDs + appliance API feature ERDs + largest appliance-specific ERD list.
#define POLLING_LIST_MAX_SIZE 653

// 0x0000 to 0x0FFF: common ERDs (all appliance types)
extern const tiny_erd_t commonErds[];
extern const uint16_t commonErdCount;

// 0x1000 to 0x1FFF: refrigeration ERDs
extern const tiny_erd_t refrigerationErds[];
extern const uint16_t refrigerationErdCount;

// 0x2000 to 0x2FFF: laundry ERDs
extern const tiny_erd_t laundryErds[];
extern const uint16_t laundryErdCount;

// 0x3000 to 0x3FFF: dishwasher ERDs
extern const tiny_erd_t dishWasherErds[];
extern const uint16_t dishWasherErdCount;

// 0x4000 to 0x4FFF: waterHeater ERDs
extern const tiny_erd_t waterHeaterErds[];
extern const uint16_t waterHeaterErdCount;

// 0x5000 to 0x5FFF: range ERDs (stoves, cooktops, ovens, etc)
extern const tiny_erd_t rangeErds[];
extern const uint16_t rangeErdCount;

// 0x7000 to 0x7FFF: air conditioning ERDs (mini split, Zoneline, etc)
extern const tiny_erd_t airConditioningErds[];
extern const uint16_t airConditioningErdCount;

// 0x8000 to 0x8FFF: water filter ERDs
extern const tiny_erd_t waterFilterErds[];
extern const uint16_t waterFilterErdCount;

// 0x9000 to 0x9FFF: small appliance ERDs (coffee makers, etc)
extern const tiny_erd_t smallApplianceErds[];
extern const uint16_t smallApplianceErdCount;

// 0xD000 to 0xDFFF: energy ERDs (all appliance types)
extern const tiny_erd_t energyErds[];
extern const uint16_t energyErdCount;

// Appliance API feature bit ERDs (all appliance types)
// These ERDs carry feature bitmaps used to determine which appliance API features are active.
// Not generated from appliance_api_erd_definitions.json; hard-coded here.
extern const tiny_erd_t applianceApiFeatureErds[];
extern const uint16_t applianceApiFeatureErdCount;

typedef struct {
  const tiny_erd_t* erdList;
  uint16_t erdCount;
} applianceTypeToErdListAndCount_t;

extern const applianceTypeToErdListAndCount_t applianceTypeToErdGroupTranslation[];
extern const uint16_t maximumApplianceType;
#endif
