/*!
 * @file
 * @brief Known string-valued ERD IDs for the MQTT adapter.
 *
 * Full HA-discovery entity definitions are NOT stored here.
 * They are fetched at runtime from compact per-category JSONL files hosted at:
 *   https://raw.githubusercontent.com/joshualongenecker/home-assistant-bridge-esphome/main/ha_discovery/
 *
 * Do not edit this file manually. Run scripts/generate_erd_lists.py to regenerate.
 */

#ifndef HA_DISCOVERY_CONFIG_H
#define HA_DISCOVERY_CONFIG_H

#include <stdint.h>

// ERDs whose value is a null-terminated ASCII string.
// The MQTT adapter publishes these as text rather than hex.
static const uint16_t ha_string_erd_ids[] = {
};
static const uint16_t ha_string_erd_count =
  (uint16_t)(sizeof(ha_string_erd_ids) / sizeof(ha_string_erd_ids[0]));

#endif
