esphome:
  name: gea-esphome-test
  friendly_name: gea-esphome-test
  name_add_mac_suffix: true

api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Allow OTA updates
ota:
  - platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework: 
    type: esp-idf

# External component configuration
# For CI testing, we use the local component directory
external_components:
  - source:
      type: local
      path: ../components
    components: [ geappliances_bridge ]

# MQTT configuration for Home Assistant
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  port: 1883
  discovery: true
  discovery_prefix: homeassistant
  clean_session: true

# UART configuration for GEA3 communication
uart:
  # UART configuration for GEA3 communication
  - id: gea3_uart
    tx_pin: GPIO21 #D6 on Xiao ESP32-C3
    rx_pin: GPIO20 #D7 on Xiao ESP32-C3
    baud_rate: 230400

  - id: gea2_uart
    tx_pin: GPIO9 # D9 on Xiao ESP32-C3
    rx_pin: GPIO10 # D10 on Xiao ESP32-C3
    baud_rate: 19200
    rx_full_threshold: 1
    rx_timeout: 1

# GE Appliances Bridge component
geappliances_bridge:
  gea3_uart_id: gea3_uart
  gea2_uart_id: gea2_uart
  # device_id: "YourDeviceId"   # Optional: Uncomment to use a custom device ID
  # mode: auto                  # Default: auto   Options: auto, subscribe, poll
  # polling_interval: 10000     # Default: 10000 ms (10 seconds), used when in polling mode
  # polling_only_publish_on_change: true  # Default: true, only publish if value changed
  # generate_device_config: false  # Default: true. Set to false to disable automatic HA MQTT discovery
