#!/usr/bin/env python3
"""
Script to compress HA discovery JSONL files into C byte arrays using
chunked compression.

Each JSONL file is split into small chunks that are independently
compressed with zlib. This allows the decompressor to process data
with a small buffer instead of needing the full decompressed data
in memory at once.
"""

import json
import sys
import zlib
from pathlib import Path


CATEGORIES = [
    "common",
    "refrigeration",
    "laundry",
    "dishwasher",
    "waterheater",
    "range",
    "airconditioning",
    "waterfilter",
    "smallappliance",
    "energy",
]

# Target decompressed chunk size (must fit in decompress_buf: 8KB).
CHUNK_TARGET_DECOMPRESSED = 4000


def category_to_cpp_name(category: str) -> str:
    return category.lower()


def compress_chunk(data: bytes) -> bytes:
    return zlib.compress(data, level=9)


def split_into_chunks(raw_data: bytes) -> list:
    """Split raw data into chunks, each decompressing to <= CHUNK_TARGET_DECOMPRESSED.
    
    Returns list of (compressed_data, decompressed_size) tuples.
    """
    chunks = []
    lines = raw_data.split(b'\n')
    
    current_lines = []
    current_raw = b''
    
    for line in lines:
        if not line:
            continue
        
        test_lines = current_lines + [line]
        test_raw = b'\n'.join(test_lines) + b'\n'
        
        if len(test_raw) > CHUNK_TARGET_DECOMPRESSED and current_lines:
            chunk_compressed = compress_chunk(current_raw)
            chunks.append((chunk_compressed, len(current_raw)))
            current_lines = [line]
            current_raw = line + b'\n'
        else:
            current_lines = test_lines
            current_raw = test_raw
    
    if current_lines:
        chunk_compressed = compress_chunk(current_raw)
        chunks.append((chunk_compressed, len(current_raw)))
    
    return chunks


def bytes_to_c_array(data: bytes, indent: int = 2) -> str:
    lines = []
    indent_str = ' ' * indent
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_values = ', '.join(f'0x{b:02x}' for b in chunk)
        comma = ',' if i + 16 < len(data) else ''
        lines.append(f'{indent_str}{hex_values}{comma}')
    return '\n'.join(lines)


def generate_header(input_dir: Path) -> str:
    lines = []
    lines.append('/*!')
    lines.append(' * @file')
    lines.append(' * @brief Compressed Home Assistant MQTT Discovery entity definitions.')
    lines.append(' *')
    lines.append(' * Chunked compression: each category is split into small independently-')
    lines.append(' * compressible chunks. This allows decompression with a small buffer.')
    lines.append(' *')
    lines.append(' * This file is auto-generated from ha_discovery JSONL files.')
    lines.append(' * Do not edit this file manually. Run scripts/compress_ha_discovery.py to regenerate.')
    lines.append(' */')
    lines.append('')
    lines.append('#ifndef HA_DISCOVERY_DATA_H')
    lines.append('#define HA_DISCOVERY_DATA_H')
    lines.append('')
    lines.append('#include <stdint.h>')
    lines.append('#include <stddef.h>')
    lines.append('')
    lines.append('/* Chunk descriptor: offset and compressed size within category data. */')
    lines.append('typedef struct {')
    lines.append('  uint32_t offset;')
    lines.append('  uint16_t size;')
    lines.append('} ha_discovery_chunk_t;')
    lines.append('')
    lines.append('/* Category descriptor: name, data pointer, chunk table, and metadata. */')
    lines.append('typedef struct {')
    lines.append('  const char* name;')
    lines.append('  const uint8_t* data;')
    lines.append('  const ha_discovery_chunk_t* chunks;')
    lines.append('  uint16_t num_chunks;')
    lines.append('  uint16_t max_decompressed_chunk;')
    lines.append('} ha_discovery_category_t;')
    lines.append('')
    
    # Process all categories
    category_data = {}
    for category in CATEGORIES:
        jsonl_path = input_dir / f'{category}.jsonl'
        if not jsonl_path.exists():
            print(f"Warning: {jsonl_path} not found, skipping", file=sys.stderr)
            continue
        
        with open(jsonl_path, 'rb') as f:
            raw_data = f.read()
        
        chunks = split_into_chunks(raw_data)
        cpp_name = category_to_cpp_name(category)
        
        all_compressed = b''.join(c for c, _ in chunks)
        
        chunk_descriptors = []
        offset = 0
        max_decompressed = 0
        for compressed, decompressed_size in chunks:
            chunk_descriptors.append((offset, len(compressed)))
            max_decompressed = max(max_decompressed, decompressed_size)
            offset += len(compressed)
        
        category_data[cpp_name] = {
            'category': category,
            'all_compressed': all_compressed,
            'chunks': chunk_descriptors,
            'num_chunks': len(chunks),
            'max_decompressed': max_decompressed,
            'raw_size': len(raw_data),
        }
    
    # Generate chunk tables and data arrays
    for cpp_name, info in category_data.items():
        lines.append(f'// {info["category"]}.jsonl chunks')
        lines.append(f'static const ha_discovery_chunk_t ha_discovery_chunk_{cpp_name}[] = {{')
        for i, (offset, size) in enumerate(info['chunks']):
            comma = ',' if i + 1 < info['num_chunks'] else ''
            lines.append(f'  {{ {offset}, {size} }}{comma}')
        lines.append('};')
        lines.append('')
        
        lines.append(f'// {info["category"]}.jsonl compressed data ({len(info["all_compressed"])} bytes from {info["raw_size"]} bytes)')
        lines.append(f'static const uint8_t ha_discovery_data_{cpp_name}[] = {{')
        lines.append(bytes_to_c_array(info['all_compressed']))
        lines.append('};')
        lines.append('')
    
    # Generate category array (C++-compatible initialization)
    lines.append('/* Category table */')
    lines.append('static const ha_discovery_category_t ha_discovery_categories[] = {')
    for cpp_name, info in category_data.items():
        lines.append(f'  {{ "{info["category"]}", ha_discovery_data_{cpp_name},')
        lines.append(f'     ha_discovery_chunk_{cpp_name},')
        lines.append(f'     {info["num_chunks"]},')
        lines.append(f'     {info["max_decompressed"]} }},')
    lines.append('};')
    lines.append('')
    lines.append(f'static const uint16_t ha_discovery_category_count = {len(category_data)};')
    lines.append('')
    lines.append('#endif')
    lines.append('')
    
    return '\n'.join(lines)
def generate_header_to_file(input_dir: Path, output_dir: Path) -> None:
    """Generate the compressed header and write it to output_dir/ha_discovery_data.h.

    Used by generate_erd_lists.py for in-process generation.
    output_dir is the repo root (parent of ha_discovery/).
    """
    output_file = output_dir / 'components' / 'geappliances_bridge' / 'ha_discovery_data.h'
    header = generate_header(input_dir)
    print(f"Writing compressed header to {output_file}")
    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, 'w') as f:
        f.write(header)


def main():
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent

    input_dir = repo_root / 'ha_discovery'
    output_file = repo_root / 'components' / 'geappliances_bridge' / 'ha_discovery_data.h'

    if not input_dir.exists():
        print(f"Error: {input_dir} does not exist. Run generate_ha_discovery.py first.", file=sys.stderr)
        sys.exit(1)

    jsonl_files = list(input_dir.glob('*.jsonl'))
    if not jsonl_files:
        print(f"Error: No JSONL files found in {input_dir}. Run generate_ha_discovery.py first.", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(jsonl_files)} JSONL files in {input_dir}")

    header = generate_header(input_dir)

    print(f"Writing compressed header to {output_file}")
    with open(output_file, 'w') as f:
        f.write(header)

    # Print summary
    total_compressed = 0
    total_uncompressed = 0
    total_chunks = 0
    max_decompressed = 0
    for category in CATEGORIES:
        jsonl_path = input_dir / f'{category}.jsonl'
        if jsonl_path.exists():
            with open(jsonl_path, 'rb') as f:
                raw_data = f.read()
            total_uncompressed += len(raw_data)
            chunks = split_into_chunks(raw_data)
            total_chunks += len(chunks)
            for compressed, decompressed_size in chunks:
                total_compressed += len(compressed)
                max_decompressed = max(max_decompressed, decompressed_size)

    ratio = total_compressed / total_uncompressed * 100 if total_uncompressed else 0
    print(f"\nCompression summary:")
    print(f"  Total uncompressed: {total_uncompressed:,} bytes")
    print(f"  Total compressed:   {total_compressed:,} bytes")
    print(f"  Total chunks:       {total_chunks}")
    print(f"  Max decompressed:   {max_decompressed:,} bytes")
    print(f"  Ratio: {ratio:.1f}%")
    print("Done!")


if __name__ == '__main__':
    main()
