#!/usr/bin/env python3
"""
Script to generate C header files from the public-appliance-api-documentation library.

Generates three files:
  1. erd_lists.h (from appliance_api_erd_definitions.json):
     ERD lists organized by appliance type for the polling bridge discovery
     phase, plus the POLLING_LIST_MAX_SIZE constant.

  2. appliance_api_feature_lists.h (from appliance_api.json):
     Feature API descriptors that map feature bits in ERDs 0x0092-0x0097 and 0x0109-0x010D to
     the associated ERD lists. Used at runtime to build the valid ERD set when
     appliance_api_parsing is enabled.

  3. ha_discovery_config.h (from appliance_api_erd_definitions.json):
     Home Assistant MQTT Discovery configuration for ERDs that carry ha_domain metadata,
     enabling automatic entity creation in Home Assistant when the bridge starts up.
"""

import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Set


def parse_erd_id(erd_id_str: str) -> int:
    """Convert ERD ID string (e.g., '0x0001') to integer."""
    return int(erd_id_str, 16)


def categorize_erds(erds: List[Dict]) -> Dict[str, List[int]]:
    """
    Categorize ERDs by hex range into appliance types.
    
    Ranges:
    0x0000 to 0x0FFF: common ERDs (all appliance types)
    0x1000 to 0x1FFF: refrigeration ERDs
    0x2000 to 0x2FFF: laundry ERDs
    0x3000 to 0x3FFF: dishwasher ERDs
    0x4000 to 0x4FFF: waterHeater ERDs
    0x5000 to 0x5FFF: range ERDs (i.e., stoves, cooktops, ovens, etc)
    0x7000 to 0x7FFF: air conditioning ERDs (i.e., mini split, Zoneline, etc)
    0x8000 to 0x8FFF: water filter ERDs
    0x9000 to 0x9FFF: small appliance ERDs (i.e., coffee makers, etc)
    0xD000 to 0xDFFF: energy ERDs (all appliance types)
    """
    categories = {
        'common': set(),
        'refrigeration': set(),
        'laundry': set(),
        'dishWasher': set(),
        'waterHeater': set(),
        'range': set(),
        'airConditioning': set(),
        'waterFilter': set(),
        'smallAppliance': set(),
        'energy': set()
    }
    
    for erd in erds:
        erd_id = parse_erd_id(erd['id'])
        
        if 0x0000 <= erd_id <= 0x0FFF:
            categories['common'].add(erd_id)
        elif 0x1000 <= erd_id <= 0x1FFF:
            categories['refrigeration'].add(erd_id)
        elif 0x2000 <= erd_id <= 0x2FFF:
            categories['laundry'].add(erd_id)
        elif 0x3000 <= erd_id <= 0x3FFF:
            categories['dishWasher'].add(erd_id)
        elif 0x4000 <= erd_id <= 0x4FFF:
            categories['waterHeater'].add(erd_id)
        elif 0x5000 <= erd_id <= 0x5FFF:
            categories['range'].add(erd_id)
        elif 0x7000 <= erd_id <= 0x7FFF:
            categories['airConditioning'].add(erd_id)
        elif 0x8000 <= erd_id <= 0x8FFF:
            categories['waterFilter'].add(erd_id)
        elif 0x9000 <= erd_id <= 0x9FFF:
            categories['smallAppliance'].add(erd_id)
        elif 0xD000 <= erd_id <= 0xDFFF:
            categories['energy'].add(erd_id)
    
    # Convert sets to sorted lists
    return {key: sorted(list(value)) for key, value in categories.items()}


def format_erd_list(erds: List[int], indent: int = 2) -> str:
    """Format a list of ERDs as C array elements."""
    if not erds:
        return ""
    
    lines = []
    indent_str = ' ' * indent
    
    for erd in erds:
        lines.append(f"{indent_str}0x{erd:04x},")
    
    return '\n'.join(lines)


def generate_header(categories: Dict[str, List[int]], polling_list_max_size: int) -> str:
    """Generate the complete erd_lists.h header file."""
    header = f"""/*!
 * @file
 * @brief Erd lists for various appliances
 * 
 * This file is auto-generated from appliance_api_erd_definitions.json
 * Do not edit this file manually. Run scripts/generate_erd_lists.py to regenerate.
 */

#ifndef ERD_LISTS_H
#define ERD_LISTS_H

#include "tiny_erd.h"

// Maximum number of ERDs that can be held in the polling list.
// Sized for the worst case: common ERDs + energy ERDs + largest appliance-specific ERD list.
#define POLLING_LIST_MAX_SIZE {polling_list_max_size}

"""
    
    # Generate each category
    category_info = [
        ('common', 'commonErds', 'commonErdCount', '0x0000 to 0x0FFF: common ERDs (all appliance types)'),
        ('refrigeration', 'refrigerationErds', 'refrigerationErdCount', '0x1000 to 0x1FFF: refrigeration ERDs'),
        ('laundry', 'laundryErds', 'laundryErdCount', '0x2000 to 0x2FFF: laundry ERDs'),
        ('dishWasher', 'dishWasherErds', 'dishWasherErdCount', '0x3000 to 0x3FFF: dishwasher ERDs'),
        ('waterHeater', 'waterHeaterErds', 'waterHeaterErdCount', '0x4000 to 0x4FFF: waterHeater ERDs'),
        ('range', 'rangeErds', 'rangeErdCount', '0x5000 to 0x5FFF: range ERDs (stoves, cooktops, ovens, etc)'),
        ('airConditioning', 'airConditioningErds', 'airConditioningErdCount', '0x7000 to 0x7FFF: air conditioning ERDs (mini split, Zoneline, etc)'),
        ('waterFilter', 'waterFilterErds', 'waterFilterErdCount', '0x8000 to 0x8FFF: water filter ERDs'),
        ('smallAppliance', 'smallApplianceErds', 'smallApplianceErdCount', '0x9000 to 0x9FFF: small appliance ERDs (coffee makers, etc)'),
        ('energy', 'energyErds', 'energyErdCount', '0xD000 to 0xDFFF: energy ERDs (all appliance types)')
    ]
    
    for category_key, array_name, count_name, description in category_info:
        erds = categories[category_key]
        header += f"// {description}\n"
        header += f"const tiny_erd_t {array_name}[] = {{\n"
        if erds:
            header += format_erd_list(erds)
            header += "\n"
        header += "};\n"
        header += f"const uint16_t {count_name} = sizeof({array_name}) / sizeof({array_name}[0]);\n\n"
    
    # Add the lookup table structure
    header += """typedef struct {
  const tiny_erd_t* erdList;
  uint16_t erdCount;
} applianceTypeToErdListAndCount_t;

const applianceTypeToErdListAndCount_t applianceTypeToErdGroupTranslation[] = {
  { waterHeaterErds, waterHeaterErdCount }, // 0x00 = Water heater
  { laundryErds, laundryErdCount }, // 0x01 = Clothes washer
  { laundryErds, laundryErdCount }, // 0x02 = Clothes dryer
  { refrigerationErds, refrigerationErdCount }, // 0x03 = Refrigerator
  { smallApplianceErds, smallApplianceErdCount }, // 0x04 = Microwave
  { rangeErds, rangeErdCount }, // 0x05 = Advantium
  { dishWasherErds, dishWasherErdCount }, // 0x06 = Dishwasher
  { rangeErds, rangeErdCount }, // 0x07 = Oven
  { rangeErds, rangeErdCount }, // 0x08 = Electric range
  { rangeErds, rangeErdCount }, // 0x09 = Gas range
  { airConditioningErds, airConditioningErdCount }, // 0x0A = Thermostat/RAC
  { rangeErds, rangeErdCount }, // 0x0B = Electric Cooktop
  { rangeErds, rangeErdCount }, // 0x0C = Pizza Oven
  { rangeErds, rangeErdCount }, // 0x0D = Gas Cooktop
  { airConditioningErds, airConditioningErdCount }, // 0x0E = Split / DFS (Duct-Free Split) AC
  { rangeErds, rangeErdCount }, // 0x0F = Hood
  { waterFilterErds, waterFilterErdCount }, // 0x10 = Point of Entry Water Filter
  { rangeErds, rangeErdCount }, // 0x11 = Induction Cooktop
  { refrigerationErds, refrigerationErdCount }, // 0x12 = Delivery Box
  { rangeErds, rangeErdCount }, // 0x13 = Kitchen Hub Vent Hood
  { airConditioningErds, airConditioningErdCount }, // 0x14 = Zoneline/PTAC
  { waterFilterErds, waterFilterErdCount }, // 0x15 = Water Softener
  { airConditioningErds, airConditioningErdCount }, // 0x16 = Portable AC
  { laundryErds, laundryErdCount }, // 0x17 = Combination Washer Dryer
  { refrigerationErds, refrigerationErdCount }, // 0x18 = Dual Zone Wine Chiller
  { refrigerationErds, refrigerationErdCount }, // 0x19 = Beverage Center
  { smallApplianceErds, smallApplianceErdCount }, // 0x1A = Coffee Brewer
  { smallApplianceErds, smallApplianceErdCount }, // 0x1B = Opal Nugget Ice Maker
  { refrigerationErds, refrigerationErdCount }, // 0x1C = In-Home Grower
  { airConditioningErds, airConditioningErdCount }, // 0x1D = Dehumidifer
  { refrigerationErds, refrigerationErdCount }, // 0x1E = Under Counter Ice Maker
  { airConditioningErds, airConditioningErdCount }, // 0x1F = Through Wall AC
  { dishWasherErds, dishWasherErdCount }, // 0x20 = F&P DishDrawer
  { smallApplianceErds, smallApplianceErdCount }, // 0x21 = Espresso Coffee Maker
  { smallApplianceErds, smallApplianceErdCount }, // 0x22 = Toaster Oven
  { airConditioningErds, airConditioningErdCount }, // 0x23 = Zoneline/VTAC
  { airConditioningErds, airConditioningErdCount }, // 0x24 = Central DFS (Duct-Free Split) Controller
  { smallApplianceErds, smallApplianceErdCount }, // 0x25 = BLE Mesh Gateway
  { smallApplianceErds, smallApplianceErdCount }, // 0x26 = Stand Mixer
  { rangeErds, rangeErdCount }, // 0x27 = Fisher & Paykel Cooktop
  { rangeErds, rangeErdCount }, // 0x28 = Fisher & Paykel Cooktop Teppanyaki
  { rangeErds, rangeErdCount }, // 0x29 = Fisher & Paykel Ventilation Downdraft
  { smallApplianceErds, smallApplianceErdCount }, // 0x2A = Smart Plug
  { smallApplianceErds, smallApplianceErdCount }, // 0x2B = Smoker
  { airConditioningErds, airConditioningErdCount }, // 0x2C = Air Handler VRF
  { laundryErds, laundryErdCount }, // 0x2D = Fabric Care Cabinet Closet
  { laundryErds, laundryErdCount }, // 0x2E = Laundry Center
  { rangeErds, rangeErdCount }, // 0x2F = Grill
  { refrigerationErds, refrigerationErdCount }, // 0x30 = Freezer
  { rangeErds, rangeErdCount }, // 0x31 = Warming Drawer
  { smallApplianceErds, smallApplianceErdCount }, // 0x32 = Vacuum Seal Drawer
  { refrigerationErds, refrigerationErdCount }, // 0x33 = Wine Cabinet
  { airConditioningErds, airConditioningErdCount }, // 0x34 = Central AC
  { rangeErds, rangeErdCount }, // 0x35 = Hearth Pizza Oven
  { smallApplianceErds, smallApplianceErdCount }, // 0x36 = Sourdough Starter
};
const uint16_t maximumApplianceType = sizeof(applianceTypeToErdGroupTranslation) / sizeof(applianceTypeToErdGroupTranslation[0]);
#endif
"""
    
    return header




def sanitize_name_for_cpp(name: str) -> str:
    """Sanitize a feature API name for use as a C++ identifier (all lowercase)."""
    result = re.sub(r'[^a-zA-Z0-9]', '_', name)
    result = re.sub(r'_+', '_', result)
    return result.strip('_').lower()


def collect_erds_for_feature(feature: Dict) -> List[int]:
    """Collect all ERD IDs for a single feature (required + optional)."""
    erds: Set[int] = set()
    for erd_entry in feature.get('required', []) + feature.get('optional', []):
        erds.add(parse_erd_id(erd_entry['erd']))
    return sorted(erds)


def collect_all_erds_for_common_feature(feature: Dict) -> List[int]:
    """Collect all ERD IDs for a single common feature."""
    erds: Set[int] = set()
    for erd_entry in feature.get('required', []) + feature.get('optional', []):
        erds.add(parse_erd_id(erd_entry['erd']))
    return sorted(erds)


def generate_appliance_api_feature_lists_header(appliance_api_data: Dict) -> str:
    """Generate the complete appliance_api_feature_lists.h header file."""

    lines: List[str] = []
    lines.append("/*!")
    lines.append(" * @file")
    lines.append(" * @brief Appliance API feature descriptors mapping feature bits to ERD lists")
    lines.append(" *")
    lines.append(" * This file is auto-generated from appliance_api.json")
    lines.append(" * Do not edit this file manually. Run scripts/generate_erd_lists.py to regenerate.")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef APPLIANCE_API_FEATURE_LISTS_H")
    lines.append("#define APPLIANCE_API_FEATURE_LISTS_H")
    lines.append("")
    lines.append("#include \"tiny_erd.h\"")
    lines.append("#include <stdint.h>")
    lines.append("")

    # -------------------------------------------------------------------------
    # Common features (ERD 0x0092)
    # -------------------------------------------------------------------------
    lines.append("// ============================================================================")
    lines.append("// Common features (ERD 0x0092)")
    lines.append("// Each feature is identified by a bitmask within the 4-byte ERD value")
    lines.append("// ============================================================================")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("  uint32_t bit_mask;")
    lines.append("  const char* name;")
    lines.append("  const tiny_erd_t* erds;")
    lines.append("  uint16_t erd_count;")
    lines.append("} common_feature_descriptor_t;")
    lines.append("")

    common = appliance_api_data.get('common', {})
    # Use the single version that exists (all versions merged; currently only v1)
    all_common_features: List[Dict] = []
    for ver_data in common.get('versions', {}).values():
        all_common_features.extend(ver_data.get('features', []))

    # Generate ERD arrays for each common feature
    for feature in all_common_features:
        sanitized = sanitize_name_for_cpp(feature['name'])
        erds = collect_all_erds_for_common_feature(feature)
        array_name = f"common_feature_{sanitized}_erds"
        if erds:
            lines.append(f"static const tiny_erd_t {array_name}[] = {{")
            for erd_id in erds:
                lines.append(f"  0x{erd_id:04x},")
            lines.append("};")
        else:
            lines.append(f"static const tiny_erd_t* {array_name} = nullptr;")
        lines.append("")

    # Generate master common feature descriptor array
    lines.append("static const common_feature_descriptor_t common_feature_descriptors[] = {")
    for feature in all_common_features:
        sanitized = sanitize_name_for_cpp(feature['name'])
        array_name = f"common_feature_{sanitized}_erds"
        mask_val = int(feature['mask'], 16)
        erds = collect_all_erds_for_common_feature(feature)
        count = len(erds)
        null_ptr = "nullptr" if count == 0 else array_name
        lines.append(f"  {{0x{mask_val:08x}, \"{feature['name']}\", {null_ptr}, {count}}},")
    lines.append("};")
    lines.append("static const uint16_t common_feature_descriptor_count =")
    lines.append("  sizeof(common_feature_descriptors) / sizeof(common_feature_descriptors[0]);")
    lines.append("")

    # -------------------------------------------------------------------------
    # Appliance Feature APIs (ERDs 0x0093-0x0097 and 0x0109-0x010D)
    # Each ERD carries: [2-byte featureType][2-byte version][4-byte feature bitmap]
    # featureType identifies the appliance API (e.g. 0x0014 = Zoneline).
    # version selects the API version.
    # Each bit in the feature bitmap corresponds to a feature's mask value.
    # -------------------------------------------------------------------------
    lines.append("// ============================================================================")
    lines.append("// Appliance Feature APIs (ERDs 0x0093-0x0097 and 0x0109-0x010D)")
    lines.append("// Each ERD value is: [2B featureType][2B version][4B feature bitmap]")
    lines.append("// One descriptor per feature per version; matched at runtime by featureType+version.")
    lines.append("// ============================================================================")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("  uint16_t feature_type;  // appliance API type (bytes 0-1 of ERD value)")
    lines.append("  uint16_t version;       // API version (bytes 2-3 of ERD value)")
    lines.append("  uint32_t bit_mask;      // feature bitmap mask (within bytes 4-7 of ERD value)")
    lines.append("  const char* name;       // human-readable \"ApiName / FeatureName\" label")
    lines.append("  const tiny_erd_t* erds;")
    lines.append("  uint16_t erd_count;")
    lines.append("} appliance_feature_api_descriptor_t;")
    lines.append("")

    feature_apis = appliance_api_data.get('featureApis', {})

    # Include only feature APIs whose featureType fits in the 10 ERD slots:
    #   0x0093-0x0097 (high byte 0-4) and 0x0109-0x010D (high byte 5-9).
    valid_feature_apis = [
        (key, api)
        for key, api in feature_apis.items()
        if (api['featureType'] >> 8) <= 9
    ]

    # Pre-compute unique array names for every (api, ver, feature) triple.
    # When two features in the same api+version share the same sanitized name,
    # append the hex mask value to make each identifier unique.
    def make_array_names(valid_feature_apis):
        """Return a dict mapping (api_key, ver, feature_index) -> unique array name."""
        result = {}
        for key, api in valid_feature_apis:
            api_sanitized = sanitize_name_for_cpp(api['name'])
            for ver, ver_data in api.get('versions', {}).items():
                # First pass: collect candidate names
                candidates = {}  # name -> list of (index, mask)
                for i, feature in enumerate(ver_data.get('features', [])):
                    feat_sanitized = sanitize_name_for_cpp(feature['name'])
                    base = f"appliance_api_{api_sanitized}_v{ver}_{feat_sanitized}_erds"
                    candidates.setdefault(base, []).append((i, int(feature['mask'], 16)))
                # Second pass: assign names, deduplicating with mask suffix
                for base, entries in candidates.items():
                    if len(entries) == 1:
                        idx, _ = entries[0]
                        result[(key, ver, idx)] = base
                    else:
                        for idx, mask in entries:
                            result[(key, ver, idx)] = f"{base[:-len('_erds')]}_m{mask:08x}_erds"
        return result

    array_names = make_array_names(valid_feature_apis)

    # Generate one ERD array per feature per version per appliance API.
    for key, api in valid_feature_apis:
        for ver, ver_data in api.get('versions', {}).items():
            for i, feature in enumerate(ver_data.get('features', [])):
                array_name = array_names[(key, ver, i)]
                erds = collect_erds_for_feature(feature)
                if erds:
                    lines.append(f"static const tiny_erd_t {array_name}[] = {{")
                    for erd_id in erds:
                        lines.append(f"  0x{erd_id:04x},")
                    lines.append("};")
                else:
                    lines.append(f"static const tiny_erd_t* {array_name} = nullptr;")
                lines.append("")

    # Generate master descriptor array: one row per feature per version.
    lines.append("static const appliance_feature_api_descriptor_t appliance_feature_api_descriptors[] = {")
    total_descriptors = 0
    for key, api in valid_feature_apis:
        ft = api['featureType']
        for ver, ver_data in api.get('versions', {}).items():
            for i, feature in enumerate(ver_data.get('features', [])):
                array_name = array_names[(key, ver, i)]
                mask_val = int(feature['mask'], 16)
                erds = collect_erds_for_feature(feature)
                count = len(erds)
                null_ptr = "nullptr" if count == 0 else array_name
                label = f"{api['name']} / {feature['name']}"
                lines.append(
                    f"  {{0x{ft:04x}, {ver}, 0x{mask_val:08x}, \"{label}\", {null_ptr}, {count}}},"
                )
                total_descriptors += 1
    lines.append("};")
    lines.append("static const uint16_t appliance_feature_api_descriptor_count =")
    lines.append("  sizeof(appliance_feature_api_descriptors) / sizeof(appliance_feature_api_descriptors[0]);")
    lines.append("")
    lines.append("#endif")
    lines.append("")

    return "\n".join(lines)


def get_erd_byte_size(erd_data: List[Dict]) -> int:
    """Compute the actual byte size of an ERD from its data field definitions.

    Each data field has an 'offset' (byte offset) and 'size' (byte count).
    Fields may overlap (bit-fields share the same bytes), so the true ERD byte
    size is the highest (offset + size) value across all fields.
    """
    if not erd_data:
        return 0
    return max((d.get('offset', 0) + d.get('size', 0)) for d in erd_data)


def get_first_enum_values(erd_data: List[Dict]) -> Dict[str, str]:
    """Return the values dict from the first enum-typed data field, or {}."""
    for d in erd_data:
        if d.get('type') == 'enum':
            return d.get('values', {})
    return {}


def _get_first_enum_field_info(erd_data: List[Dict]):
    """Return (values_dict, field_size) for the first enum-typed data field.

    field_size is the byte width of the enum field (used to build the hex
    extraction slice in value templates).  Falls back to ({}, 1) when no
    enum field is present.
    """
    for d in erd_data:
        if d.get('type') == 'enum':
            return d.get('values', {}), max(1, d.get('size', 1))
    return {}, 1


def _unit_to_ha(unit: str) -> str:
    """Convert an API unit string to the Home Assistant display unit."""
    return {'degF': '\u00b0F', 'degC': '\u00b0C'}.get(unit, unit)


def _c_str(s: str) -> str:
    """Wrap a Python string as a C string literal (double-quoted, escaped)."""
    escaped = s.replace('\\', '\\\\').replace('"', '\\"')
    return f'"{escaped}"'


def _compute_sensor_value_template(scaling_factor: int, data_size: int) -> str:
    """Return the Jinja2 value_template for a numeric sensor ERD."""
    if scaling_factor > 1:
        if scaling_factor == 10:
            dp = 1
        elif scaling_factor == 100:
            dp = 2
        else:
            dp = 3
        return f'{{{{ (value | int(base=16)) / {scaling_factor} | round({dp}) }}}}'
    return '{{ value | int(base=16) }}'


def _compute_binary_sensor_value_template(data_size: int) -> str:
    """Return value_template for a binary_sensor ERD.

    For single-byte ERDs the raw hex payload ('00'/'01') already matches
    payload_on/payload_off, so no template is needed.  For multi-byte ERDs
    we slice the first two hex characters to extract just the first byte.
    """
    return '{{ value[:2] }}' if data_size > 1 else ''


def _select_options_and_templates(enum_values: Dict[str, str], data_size: int):
    """Build options_json, value_template and command_template for a select entity.

    'Request Consumed' (value 255) is excluded from selectable options.
    Returns (options_json_str, value_template_str, command_template_str).
    """
    # Filter out 'Request Consumed' (255) and sort by numeric key
    valid_pairs = sorted(
        [(int(k), v) for k, v in enum_values.items() if v != 'Request Consumed'],
        key=lambda x: x[0]
    )
    if not valid_pairs:
        return ('[]', '', '')

    hex_chars = data_size * 2

    # Build value_template: map hex string -> option name
    hex_to_name = ', '.join(
        f"'{k:0{hex_chars}x}': '{v}'" for k, v in valid_pairs
    )
    value_template = f"{{{{ {{{hex_to_name}}}.get(value[:{hex_chars}], 'Unknown') }}}}"

    # Build command_template: map option name -> hex string
    name_to_hex = ', '.join(
        f"'{v}': '{k:0{hex_chars}x}'" for k, v in valid_pairs
    )
    command_template = f"{{{{ {{{name_to_hex}}}[value] }}}}"

    # Build options JSON array
    option_names = [v for _, v in valid_pairs]
    options_json = '[' + ', '.join(f'"{name}"' for name in option_names) + ']'

    return (options_json, value_template, command_template)


def _enum_sensor_value_template(enum_values: Dict[str, str], field_size: int) -> str:
    """Build value_template for a read-only enum sensor.

    Maps hex byte values to their human-readable label.  Works the same as the
    select value_template but without options or command_template.
    'Request Consumed' (255) is excluded.
    Falls back to showing the raw first-byte hex string when no valid mappings
    exist.
    """
    valid_pairs = sorted(
        [(int(k), v) for k, v in enum_values.items() if v != 'Request Consumed'],
        key=lambda x: x[0]
    )
    if not valid_pairs:
        return '{{ value[:2] }}'

    hex_chars = field_size * 2
    hex_to_name = ', '.join(
        f"'{k:0{hex_chars}x}': '{v}'" for k, v in valid_pairs
    )
    return f"{{{{ {{{hex_to_name}}}.get(value[:{hex_chars}], 'Unknown') }}}}"


def _strip_pair_role_word(name: str) -> str:
    """Remove trailing or standalone 'Status'/'Request' words from a paired-ERD name.

    Examples:
        'Fan Configuration in Cooling Status'  -> 'Fan Configuration in Cooling'
        'Freeze Sentinel Request'               -> 'Freeze Sentinel'
    """
    # Strip the word wherever it appears as a complete word (word boundaries)
    result = re.sub(r'\b(?:Status|Request)\b', '', name, flags=re.IGNORECASE)
    # Collapse multiple spaces and strip surrounding whitespace
    result = re.sub(r'\s+', ' ', result).strip()
    return result


def _number_command_template(data_size: int, scaling_factor: int) -> str:
    """Return command_template for a number entity."""
    hex_chars = data_size * 2
    if scaling_factor > 1:
        return f"{{{{ '%0{hex_chars}x' % ((value | float) * {scaling_factor} | int) }}}}"
    return f"{{{{ '%0{hex_chars}x' % (value | int) }}}}"


def generate_ha_discovery_header(erds: List[Dict]) -> str:
    """Generate ha_discovery_config.h from ERDs that have ha_domain metadata.

    Each annotated ERD produces one entry in the ha_erd_discovery_configs[] array.
    The C++ bridge reads this array at startup and publishes an MQTT Discovery
    payload for each entry, causing Home Assistant to auto-create entities.
    """
    # Build a lookup dict: ERD id string -> ERD dict for paired-ERD resolution
    erd_by_id: Dict[str, Dict] = {e['id']: e for e in erds}

    lines: List[str] = []
    lines.append('/*!')
    lines.append(' * @file')
    lines.append(' * @brief Home Assistant MQTT Discovery configuration per ERD')
    lines.append(' *')
    lines.append(' * This file is auto-generated from appliance_api_erd_definitions.json')
    lines.append(' * Do not edit this file manually. Run scripts/generate_erd_lists.py to regenerate.')
    lines.append(' */')
    lines.append('')
    lines.append('#ifndef HA_DISCOVERY_CONFIG_H')
    lines.append('#define HA_DISCOVERY_CONFIG_H')
    lines.append('')
    lines.append('#include <stdint.h>')
    lines.append('')
    lines.append('typedef struct {')
    lines.append('  uint16_t erd_id;')
    lines.append('  const char* name;')
    lines.append('  const char* ha_domain;')
    lines.append('  const char* unit_of_measurement;  /* "" if none */')
    lines.append('  const char* device_class;          /* "" if none */')
    lines.append('  const char* state_class;           /* "" if none */')
    lines.append('  uint32_t scaling_factor;           /* 1 if no scaling */')
    lines.append('  uint8_t data_size;                 /* ERD payload byte count */')
    lines.append('  uint16_t paired_erd_id;            /* 0 if no pair */')
    lines.append('  const char* pair_role;             /* "status", "request", or "" */')
    lines.append('  const char* value_template;        /* Jinja2 template for state values; "" if none */')
    lines.append('  const char* command_template;      /* Jinja2 template for command payloads; "" if none */')
    lines.append('  const char* options_json;          /* JSON array of select options; "" if not select */')
    lines.append('} ha_erd_discovery_config_t;')
    lines.append('')
    lines.append('static const ha_erd_discovery_config_t ha_erd_discovery_configs[] = {')

    ha_erds = [e for e in erds if 'ha_domain' in e]
    for erd in ha_erds:
        erd_id_int = parse_erd_id(erd['id'])
        name = erd.get('name', '')
        ha_domain = erd.get('ha_domain', '')
        unit_raw = erd.get('unit_of_measurement') or ''
        unit = _unit_to_ha(unit_raw)
        device_class = erd.get('device_class') or ''
        state_class = erd.get('state_class') or ''
        scaling_factor = int(erd.get('scaling_factor') or 1)
        pair_role = erd.get('pair_role') or ''
        paired_erd_str = erd.get('paired_erd') or ''
        paired_erd_id = parse_erd_id(paired_erd_str) if paired_erd_str else 0

        # Strip "Status"/"Request" role words from names on paired ERDs so both
        # sides of a pair share a clean base name (e.g. "Fan Configuration in
        # Cooling" instead of "Fan Configuration in Cooling Status/Request").
        display_name = _strip_pair_role_word(name) if pair_role else name

        erd_data = erd.get('data', [])
        data_size = get_erd_byte_size(erd_data)
        if data_size == 0:
            data_size = 1  # safe fallback

        # --- Compute templates ---
        value_template = ''
        command_template = ''
        options_json = ''

        if ha_domain == 'sensor':
            if device_class == 'enum':
                # Build a text-label mapping so HA shows human-readable names
                # instead of a raw decimal number.
                enum_field_values, field_size = _get_first_enum_field_info(erd_data)
                value_template = _enum_sensor_value_template(enum_field_values, field_size)
            elif scaling_factor > 1 or (data_size <= 4 and device_class != ''):
                value_template = _compute_sensor_value_template(scaling_factor, data_size)
            elif data_size <= 4:
                value_template = _compute_sensor_value_template(scaling_factor, data_size)
            # For large multi-field sensor ERDs (data_size > 4) leave value_template empty;
            # the bridge will publish the raw hex string.

        elif ha_domain == 'binary_sensor':
            value_template = _compute_binary_sensor_value_template(data_size)

        elif ha_domain == 'switch':
            # State is read from the paired status ERD; derive its data_size
            if paired_erd_str and paired_erd_str in erd_by_id:
                status_erd = erd_by_id[paired_erd_str]
                status_data_size = get_erd_byte_size(status_erd.get('data', []))
                if status_data_size == 0:
                    status_data_size = 1
                value_template = _compute_binary_sensor_value_template(status_data_size)
            # No command_template for switch – payload_on/off handles it

        elif ha_domain == 'select':
            enum_values = get_first_enum_values(erd_data)
            if enum_values:
                options_json, value_template, command_template = \
                    _select_options_and_templates(enum_values, data_size)

        elif ha_domain == 'number':
            if paired_erd_str and paired_erd_str in erd_by_id:
                status_erd = erd_by_id[paired_erd_str]
                status_scale = int(status_erd.get('scaling_factor') or 1)
                value_template = _compute_sensor_value_template(status_scale, data_size)
            else:
                value_template = _compute_sensor_value_template(scaling_factor, data_size)
            command_template = _number_command_template(data_size, scaling_factor)

        # button: no value_template or command_template (payload_press handled in C++)

        # Format the struct initialiser
        fields = [
            f'0x{erd_id_int:04x}',
            _c_str(display_name),
            _c_str(ha_domain),
            _c_str(unit),
            _c_str(device_class),
            _c_str(state_class),
            str(scaling_factor),
            str(data_size),
            f'0x{paired_erd_id:04x}',
            _c_str(pair_role),
            _c_str(value_template),
            _c_str(command_template),
            _c_str(options_json),
        ]
        lines.append(f'  /* {erd["id"]} {name} */')
        lines.append('  {' + ', '.join(fields) + '},')

    lines.append('};')
    lines.append('')
    lines.append('static const uint16_t ha_erd_discovery_config_count =')
    lines.append('  (uint16_t)(sizeof(ha_erd_discovery_configs) / sizeof(ha_erd_discovery_configs[0]));')
    lines.append('')
    lines.append('#endif')
    lines.append('')

    return '\n'.join(lines)


def main():
    """Main entry point for the script."""
    # Determine paths relative to script location
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent

    # -------------------------------------------------------------------------
    # Generate erd_lists.h from appliance_api_erd_definitions.json
    # -------------------------------------------------------------------------
    json_file = repo_root / 'lib' / 'public-appliance-api-documentation' / 'appliance_api_erd_definitions.json'
    output_file = repo_root / 'components' / 'geappliances_bridge' / 'erd_lists.h'

    if not json_file.exists():
        print(f"Error: Could not find {json_file}", file=sys.stderr)
        print("Make sure git submodules are initialized: git submodule update --init --recursive", file=sys.stderr)
        sys.exit(1)

    # Read and parse JSON
    print(f"Reading ERD definitions from {json_file}")
    with open(json_file, 'r') as f:
        data = json.load(f)

    erds = data.get('erds', [])
    print(f"Found {len(erds)} ERD definitions")

    # Categorize ERDs
    categories = categorize_erds(erds)

    # Print statistics
    print("\nERD counts by category:")
    for category, erd_list in categories.items():
        print(f"  {category}: {len(erd_list)}")

    # Calculate required POLLING_LIST_MAX_SIZE.
    # The polling list holds: common ERDs + energy ERDs + appliance-specific ERDs.
    # Use the worst case across all appliance-specific categories.
    appliance_specific_categories = [
        'waterHeater', 'laundry', 'refrigeration', 'smallAppliance',
        'range', 'dishWasher', 'airConditioning', 'waterFilter'
    ]
    max_appliance_erds = max(len(categories[cat]) for cat in appliance_specific_categories)
    common_erds_count = len(categories['common'])
    energy_erds_count = len(categories['energy'])
    polling_list_max_size = common_erds_count + energy_erds_count + max_appliance_erds
    print(f"\nPolling list size check:")
    print(f"  common ERDs: {common_erds_count}, energy ERDs: {energy_erds_count}, max appliance ERDs: {max_appliance_erds}")
    print(f"  POLLING_LIST_MAX_SIZE: {polling_list_max_size}")

    # Generate header (includes POLLING_LIST_MAX_SIZE)
    header_content = generate_header(categories, polling_list_max_size)

    # Write output
    print(f"\nWriting generated header to {output_file}")
    with open(output_file, 'w') as f:
        f.write(header_content)

    # -------------------------------------------------------------------------
    # Generate appliance_api_feature_lists.h from appliance_api.json
    # -------------------------------------------------------------------------
    api_json_file = repo_root / 'lib' / 'public-appliance-api-documentation' / 'appliance_api.json'
    api_output_file = repo_root / 'components' / 'geappliances_bridge' / 'appliance_api_feature_lists.h'

    if not api_json_file.exists():
        print(f"Error: Could not find {api_json_file}", file=sys.stderr)
        print("Make sure git submodules are initialized: git submodule update --init --recursive", file=sys.stderr)
        sys.exit(1)

    print(f"\nReading appliance API definitions from {api_json_file}")
    with open(api_json_file, 'r') as f:
        appliance_api_data = json.load(f)

    feature_apis = appliance_api_data.get('featureApis', {})
    common_features = appliance_api_data.get('common', {})
    valid_feature_apis = [api for api in feature_apis.values() if (api['featureType'] >> 8) <= 9]
    print(f"Found {len(feature_apis)} feature APIs ({len(valid_feature_apis)} within ERDs 0x0093-0x0097 and 0x0109-0x010D)")
    common_ver_count = sum(
        len(vd.get('features', []))
        for vd in common_features.get('versions', {}).values()
    )
    print(f"Found {common_ver_count} common features (ERD 0x0092)")

    api_header_content = generate_appliance_api_feature_lists_header(appliance_api_data)

    print(f"\nWriting generated header to {api_output_file}")
    with open(api_output_file, 'w') as f:
        f.write(api_header_content)

    # -------------------------------------------------------------------------
    # Generate ha_discovery_config.h from appliance_api_erd_definitions.json
    # -------------------------------------------------------------------------
    ha_output_file = repo_root / 'components' / 'geappliances_bridge' / 'ha_discovery_config.h'

    ha_erds = [e for e in erds if 'ha_domain' in e]
    print(f"\nFound {len(ha_erds)} ERDs with ha_domain metadata for HA MQTT Discovery")

    ha_header_content = generate_ha_discovery_header(erds)

    print(f"\nWriting generated header to {ha_output_file}")
    with open(ha_output_file, 'w') as f:
        f.write(ha_header_content)

    print("Done!")


if __name__ == '__main__':
    main()
