#!/usr/bin/env python3
"""
Script to generate C header files from the public-appliance-api-documentation library.

Generates two files:
  1. erd_lists.h (from appliance_api_erd_definitions.json):
     ERD lists organized by appliance type for the polling bridge discovery
     phase, plus the POLLING_LIST_MAX_SIZE constant.

  2. appliance_api_feature_lists.h (from appliance_api.json):
     Feature API descriptors that map feature bits in ERDs 0x0092-0x0095 to
     the associated ERD lists. Used at runtime to build the valid ERD set when
     appliance_api_parsing is enabled.
"""

import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Set


def parse_erd_id(erd_id_str: str) -> int:
    """Convert ERD ID string (e.g., '0x0001') to integer."""
    return int(erd_id_str, 16)


def categorize_erds(erds: List[Dict]) -> Dict[str, List[int]]:
    """
    Categorize ERDs by hex range into appliance types.
    
    Ranges:
    0x0000 to 0x0FFF: common ERDs (all appliance types)
    0x1000 to 0x1FFF: refrigeration ERDs
    0x2000 to 0x2FFF: laundry ERDs
    0x3000 to 0x3FFF: dishwasher ERDs
    0x4000 to 0x4FFF: waterHeater ERDs
    0x5000 to 0x5FFF: range ERDs (i.e., stoves, cooktops, ovens, etc)
    0x7000 to 0x7FFF: air conditioning ERDs (i.e., mini split, Zoneline, etc)
    0x8000 to 0x8FFF: water filter ERDs
    0x9000 to 0x9FFF: small appliance ERDs (i.e., coffee makers, etc)
    0xD000 to 0xDFFF: energy ERDs (all appliance types)
    """
    categories = {
        'common': set(),
        'refrigeration': set(),
        'laundry': set(),
        'dishWasher': set(),
        'waterHeater': set(),
        'range': set(),
        'airConditioning': set(),
        'waterFilter': set(),
        'smallAppliance': set(),
        'energy': set()
    }
    
    for erd in erds:
        erd_id = parse_erd_id(erd['id'])
        
        if 0x0000 <= erd_id <= 0x0FFF:
            categories['common'].add(erd_id)
        elif 0x1000 <= erd_id <= 0x1FFF:
            categories['refrigeration'].add(erd_id)
        elif 0x2000 <= erd_id <= 0x2FFF:
            categories['laundry'].add(erd_id)
        elif 0x3000 <= erd_id <= 0x3FFF:
            categories['dishWasher'].add(erd_id)
        elif 0x4000 <= erd_id <= 0x4FFF:
            categories['waterHeater'].add(erd_id)
        elif 0x5000 <= erd_id <= 0x5FFF:
            categories['range'].add(erd_id)
        elif 0x7000 <= erd_id <= 0x7FFF:
            categories['airConditioning'].add(erd_id)
        elif 0x8000 <= erd_id <= 0x8FFF:
            categories['waterFilter'].add(erd_id)
        elif 0x9000 <= erd_id <= 0x9FFF:
            categories['smallAppliance'].add(erd_id)
        elif 0xD000 <= erd_id <= 0xDFFF:
            categories['energy'].add(erd_id)
    
    # Convert sets to sorted lists
    return {key: sorted(list(value)) for key, value in categories.items()}


def format_erd_list(erds: List[int], indent: int = 2) -> str:
    """Format a list of ERDs as C array elements."""
    if not erds:
        return ""
    
    lines = []
    indent_str = ' ' * indent
    
    for erd in erds:
        lines.append(f"{indent_str}0x{erd:04x},")
    
    return '\n'.join(lines)


def generate_header(categories: Dict[str, List[int]], polling_list_max_size: int) -> str:
    """Generate the complete erd_lists.h header file."""
    header = f"""/*!
 * @file
 * @brief Erd lists for various appliances
 * 
 * This file is auto-generated from appliance_api_erd_definitions.json
 * Do not edit this file manually. Run scripts/generate_erd_lists.py to regenerate.
 */

#ifndef ERD_LISTS_H
#define ERD_LISTS_H

#include "tiny_erd.h"

// Maximum number of ERDs that can be held in the polling list.
// Sized for the worst case: common ERDs + energy ERDs + largest appliance-specific ERD list.
#define POLLING_LIST_MAX_SIZE {polling_list_max_size}

"""
    
    # Generate each category
    category_info = [
        ('common', 'commonErds', 'commonErdCount', '0x0000 to 0x0FFF: common ERDs (all appliance types)'),
        ('refrigeration', 'refrigerationErds', 'refrigerationErdCount', '0x1000 to 0x1FFF: refrigeration ERDs'),
        ('laundry', 'laundryErds', 'laundryErdCount', '0x2000 to 0x2FFF: laundry ERDs'),
        ('dishWasher', 'dishWasherErds', 'dishWasherErdCount', '0x3000 to 0x3FFF: dishwasher ERDs'),
        ('waterHeater', 'waterHeaterErds', 'waterHeaterErdCount', '0x4000 to 0x4FFF: waterHeater ERDs'),
        ('range', 'rangeErds', 'rangeErdCount', '0x5000 to 0x5FFF: range ERDs (stoves, cooktops, ovens, etc)'),
        ('airConditioning', 'airConditioningErds', 'airConditioningErdCount', '0x7000 to 0x7FFF: air conditioning ERDs (mini split, Zoneline, etc)'),
        ('waterFilter', 'waterFilterErds', 'waterFilterErdCount', '0x8000 to 0x8FFF: water filter ERDs'),
        ('smallAppliance', 'smallApplianceErds', 'smallApplianceErdCount', '0x9000 to 0x9FFF: small appliance ERDs (coffee makers, etc)'),
        ('energy', 'energyErds', 'energyErdCount', '0xD000 to 0xDFFF: energy ERDs (all appliance types)')
    ]
    
    for category_key, array_name, count_name, description in category_info:
        erds = categories[category_key]
        header += f"// {description}\n"
        header += f"const tiny_erd_t {array_name}[] = {{\n"
        if erds:
            header += format_erd_list(erds)
            header += "\n"
        header += "};\n"
        header += f"const uint16_t {count_name} = sizeof({array_name}) / sizeof({array_name}[0]);\n\n"
    
    # Add the lookup table structure
    header += """typedef struct {
  const tiny_erd_t* erdList;
  uint16_t erdCount;
} applianceTypeToErdListAndCount_t;

const applianceTypeToErdListAndCount_t applianceTypeToErdGroupTranslation[] = {
  { waterHeaterErds, waterHeaterErdCount }, // 0x00 = Water heater
  { laundryErds, laundryErdCount }, // 0x01 = Clothes washer
  { laundryErds, laundryErdCount }, // 0x02 = Clothes dryer
  { refrigerationErds, refrigerationErdCount }, // 0x03 = Refrigerator
  { smallApplianceErds, smallApplianceErdCount }, // 0x04 = Microwave
  { rangeErds, rangeErdCount }, // 0x05 = Advantium
  { dishWasherErds, dishWasherErdCount }, // 0x06 = Dishwasher
  { rangeErds, rangeErdCount }, // 0x07 = Oven
  { rangeErds, rangeErdCount }, // 0x08 = Electric range
  { rangeErds, rangeErdCount }, // 0x09 = Gas range
  { airConditioningErds, airConditioningErdCount }, // 0x0A = Thermostat/RAC
  { rangeErds, rangeErdCount }, // 0x0B = Electric Cooktop
  { rangeErds, rangeErdCount }, // 0x0C = Pizza Oven
  { rangeErds, rangeErdCount }, // 0x0D = Gas Cooktop
  { airConditioningErds, airConditioningErdCount }, // 0x0E = Split / DFS (Duct-Free Split) AC
  { rangeErds, rangeErdCount }, // 0x0F = Hood
  { waterFilterErds, waterFilterErdCount }, // 0x10 = Point of Entry Water Filter
  { rangeErds, rangeErdCount }, // 0x11 = Induction Cooktop
  { refrigerationErds, refrigerationErdCount }, // 0x12 = Delivery Box
  { rangeErds, rangeErdCount }, // 0x13 = Kitchen Hub Vent Hood
  { airConditioningErds, airConditioningErdCount }, // 0x14 = Zoneline/PTAC
  { waterFilterErds, waterFilterErdCount }, // 0x15 = Water Softener
  { airConditioningErds, airConditioningErdCount }, // 0x16 = Portable AC
  { laundryErds, laundryErdCount }, // 0x17 = Combination Washer Dryer
  { refrigerationErds, refrigerationErdCount }, // 0x18 = Dual Zone Wine Chiller
  { refrigerationErds, refrigerationErdCount }, // 0x19 = Beverage Center
  { smallApplianceErds, smallApplianceErdCount }, // 0x1A = Coffee Brewer
  { smallApplianceErds, smallApplianceErdCount }, // 0x1B = Opal Nugget Ice Maker
  { refrigerationErds, refrigerationErdCount }, // 0x1C = In-Home Grower
  { airConditioningErds, airConditioningErdCount }, // 0x1D = Dehumidifer
  { refrigerationErds, refrigerationErdCount }, // 0x1E = Under Counter Ice Maker
  { airConditioningErds, airConditioningErdCount }, // 0x1F = Through Wall AC
  { dishWasherErds, dishWasherErdCount }, // 0x20 = F&P DishDrawer
  { smallApplianceErds, smallApplianceErdCount }, // 0x21 = Espresso Coffee Maker
  { smallApplianceErds, smallApplianceErdCount }, // 0x22 = Toaster Oven
  { airConditioningErds, airConditioningErdCount }, // 0x23 = Zoneline/VTAC
  { airConditioningErds, airConditioningErdCount }, // 0x24 = Central DFS (Duct-Free Split) Controller
  { smallApplianceErds, smallApplianceErdCount }, // 0x25 = BLE Mesh Gateway
  { smallApplianceErds, smallApplianceErdCount }, // 0x26 = Stand Mixer
  { rangeErds, rangeErdCount }, // 0x27 = Fisher & Paykel Cooktop
  { rangeErds, rangeErdCount }, // 0x28 = Fisher & Paykel Cooktop Teppanyaki
  { rangeErds, rangeErdCount }, // 0x29 = Fisher & Paykel Ventilation Downdraft
  { smallApplianceErds, smallApplianceErdCount }, // 0x2A = Smart Plug
  { smallApplianceErds, smallApplianceErdCount }, // 0x2B = Smoker
  { airConditioningErds, airConditioningErdCount }, // 0x2C = Air Handler VRF
  { laundryErds, laundryErdCount }, // 0x2D = Fabric Care Cabinet Closet
  { laundryErds, laundryErdCount }, // 0x2E = Laundry Center
  { rangeErds, rangeErdCount }, // 0x2F = Grill
  { refrigerationErds, refrigerationErdCount }, // 0x30 = Freezer
  { rangeErds, rangeErdCount }, // 0x31 = Warming Drawer
  { smallApplianceErds, smallApplianceErdCount }, // 0x32 = Vacuum Seal Drawer
  { refrigerationErds, refrigerationErdCount }, // 0x33 = Wine Cabinet
  { airConditioningErds, airConditioningErdCount }, // 0x34 = Central AC
  { rangeErds, rangeErdCount }, // 0x35 = Hearth Pizza Oven
  { smallApplianceErds, smallApplianceErdCount }, // 0x36 = Sourdough Starter
};
const uint16_t maximumApplianceType = sizeof(applianceTypeToErdGroupTranslation) / sizeof(applianceTypeToErdGroupTranslation[0]);
#endif
"""
    
    return header




def sanitize_name_for_cpp(name: str) -> str:
    """Sanitize a feature API name for use as a C++ identifier (all lowercase)."""
    result = re.sub(r'[^a-zA-Z0-9]', '_', name)
    result = re.sub(r'_+', '_', result)
    return result.strip('_').lower()


def collect_all_erds_for_feature_api(api: Dict) -> List[int]:
    """Collect all unique ERD IDs from all versions and inner features of a feature API."""
    erds: Set[int] = set()
    for ver_data in api.get('versions', {}).values():
        for feature in ver_data.get('features', []):
            for erd_entry in feature.get('required', []) + feature.get('optional', []):
                erds.add(parse_erd_id(erd_entry['erd']))
    return sorted(erds)


def collect_all_erds_for_common_feature(feature: Dict) -> List[int]:
    """Collect all ERD IDs for a single common feature."""
    erds: Set[int] = set()
    for erd_entry in feature.get('required', []) + feature.get('optional', []):
        erds.add(parse_erd_id(erd_entry['erd']))
    return sorted(erds)


def generate_appliance_api_feature_lists_header(appliance_api_data: Dict) -> str:
    """Generate the complete appliance_api_feature_lists.h header file."""

    lines: List[str] = []
    lines.append("/*!")
    lines.append(" * @file")
    lines.append(" * @brief Appliance API feature descriptors mapping feature bits to ERD lists")
    lines.append(" *")
    lines.append(" * This file is auto-generated from appliance_api.json")
    lines.append(" * Do not edit this file manually. Run scripts/generate_erd_lists.py to regenerate.")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef APPLIANCE_API_FEATURE_LISTS_H")
    lines.append("#define APPLIANCE_API_FEATURE_LISTS_H")
    lines.append("")
    lines.append("#include \"tiny_erd.h\"")
    lines.append("#include <stdint.h>")
    lines.append("")

    # -------------------------------------------------------------------------
    # Common features (ERD 0x0092)
    # -------------------------------------------------------------------------
    lines.append("// ============================================================================")
    lines.append("// Common features (ERD 0x0092)")
    lines.append("// Each feature is identified by a bitmask within the 4-byte ERD value")
    lines.append("// ============================================================================")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("  uint32_t bit_mask;")
    lines.append("  const char* name;")
    lines.append("  const tiny_erd_t* erds;")
    lines.append("  uint16_t erd_count;")
    lines.append("} common_feature_descriptor_t;")
    lines.append("")

    common = appliance_api_data.get('common', {})
    # Use the single version that exists (all versions merged; currently only v1)
    all_common_features: List[Dict] = []
    for ver_data in common.get('versions', {}).values():
        all_common_features.extend(ver_data.get('features', []))

    # Generate ERD arrays for each common feature
    for feature in all_common_features:
        sanitized = sanitize_name_for_cpp(feature['name'])
        erds = collect_all_erds_for_common_feature(feature)
        array_name = f"common_feature_{sanitized}_erds"
        if erds:
            lines.append(f"static const tiny_erd_t {array_name}[] = {{")
            for erd_id in erds:
                lines.append(f"  0x{erd_id:04x},")
            lines.append("};")
        else:
            lines.append(f"static const tiny_erd_t* {array_name} = nullptr;")
        lines.append("")

    # Generate master common feature descriptor array
    lines.append("static const common_feature_descriptor_t common_feature_descriptors[] = {")
    for feature in all_common_features:
        sanitized = sanitize_name_for_cpp(feature['name'])
        array_name = f"common_feature_{sanitized}_erds"
        mask_val = int(feature['mask'], 16)
        erds = collect_all_erds_for_common_feature(feature)
        count = len(erds)
        null_ptr = "nullptr" if count == 0 else array_name
        lines.append(f"  {{0x{mask_val:08x}, \"{feature['name']}\", {null_ptr}, {count}}},")
    lines.append("};")
    lines.append("static const uint16_t common_feature_descriptor_count =")
    lines.append("  sizeof(common_feature_descriptors) / sizeof(common_feature_descriptors[0]);")
    lines.append("")

    # -------------------------------------------------------------------------
    # Appliance Feature APIs (ERDs 0x0093-0x0095)
    # featureType = (erd_index << 8) | bit_position
    # erd_index: 0=ERD 0x0093, 1=ERD 0x0094, 2=ERD 0x0095
    # -------------------------------------------------------------------------
    lines.append("// ============================================================================")
    lines.append("// Appliance Feature APIs (ERDs 0x0093 to 0x0095)")
    lines.append("// featureType = (erd_index << 8) | bit_position")
    lines.append("// erd_index: 0=ERD 0x0093, 1=ERD 0x0094, 2=ERD 0x0095")
    lines.append("// ============================================================================")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("  uint8_t erd_index;      // 0=0x0093, 1=0x0094, 2=0x0095")
    lines.append("  uint8_t bit_position;   // bit position within the 8-byte ERD value")
    lines.append("  const char* name;")
    lines.append("  const tiny_erd_t* erds;")
    lines.append("  uint16_t erd_count;")
    lines.append("} appliance_feature_api_descriptor_t;")
    lines.append("")

    feature_apis = appliance_api_data.get('featureApis', {})

    # Filter: only include feature APIs that map to ERDs 0x0093-0x0095 (erd_index 0-2)
    valid_feature_apis = [
        (key, api)
        for key, api in feature_apis.items()
        if (api['featureType'] >> 8) <= 2
    ]

    # Generate ERD arrays for each feature API
    for key, api in valid_feature_apis:
        sanitized = sanitize_name_for_cpp(api['name'])
        erds = collect_all_erds_for_feature_api(api)
        array_name = f"appliance_api_{sanitized}_erds"
        if erds:
            lines.append(f"static const tiny_erd_t {array_name}[] = {{")
            for erd_id in erds:
                lines.append(f"  0x{erd_id:04x},")
            lines.append("};")
        else:
            lines.append(f"static const tiny_erd_t* {array_name} = nullptr;")
        lines.append("")

    # Generate master appliance feature API descriptor array
    lines.append("static const appliance_feature_api_descriptor_t appliance_feature_api_descriptors[] = {")
    for key, api in valid_feature_apis:
        sanitized = sanitize_name_for_cpp(api['name'])
        array_name = f"appliance_api_{sanitized}_erds"
        ft = api['featureType']
        erd_index = ft >> 8
        bit_pos = ft & 0xFF
        erds = collect_all_erds_for_feature_api(api)
        count = len(erds)
        null_ptr = "nullptr" if count == 0 else array_name
        lines.append(f"  {{{erd_index}, {bit_pos}, \"{api['name']}\", {null_ptr}, {count}}},")
    lines.append("};")
    lines.append("static const uint16_t appliance_feature_api_descriptor_count =")
    lines.append("  sizeof(appliance_feature_api_descriptors) / sizeof(appliance_feature_api_descriptors[0]);")
    lines.append("")
    lines.append("#endif")
    lines.append("")

    return "\n".join(lines)


def main():
    """Main entry point for the script."""
    # Determine paths relative to script location
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent

    # -------------------------------------------------------------------------
    # Generate erd_lists.h from appliance_api_erd_definitions.json
    # -------------------------------------------------------------------------
    json_file = repo_root / 'lib' / 'public-appliance-api-documentation' / 'appliance_api_erd_definitions.json'
    output_file = repo_root / 'components' / 'geappliances_bridge' / 'erd_lists.h'

    if not json_file.exists():
        print(f"Error: Could not find {json_file}", file=sys.stderr)
        print("Make sure git submodules are initialized: git submodule update --init --recursive", file=sys.stderr)
        sys.exit(1)

    # Read and parse JSON
    print(f"Reading ERD definitions from {json_file}")
    with open(json_file, 'r') as f:
        data = json.load(f)

    erds = data.get('erds', [])
    print(f"Found {len(erds)} ERD definitions")

    # Categorize ERDs
    categories = categorize_erds(erds)

    # Print statistics
    print("\nERD counts by category:")
    for category, erd_list in categories.items():
        print(f"  {category}: {len(erd_list)}")

    # Calculate required POLLING_LIST_MAX_SIZE.
    # The polling list holds: common ERDs + energy ERDs + appliance-specific ERDs.
    # Use the worst case across all appliance-specific categories.
    appliance_specific_categories = [
        'waterHeater', 'laundry', 'refrigeration', 'smallAppliance',
        'range', 'dishWasher', 'airConditioning', 'waterFilter'
    ]
    max_appliance_erds = max(len(categories[cat]) for cat in appliance_specific_categories)
    common_erds_count = len(categories['common'])
    energy_erds_count = len(categories['energy'])
    polling_list_max_size = common_erds_count + energy_erds_count + max_appliance_erds
    print(f"\nPolling list size check:")
    print(f"  common ERDs: {common_erds_count}, energy ERDs: {energy_erds_count}, max appliance ERDs: {max_appliance_erds}")
    print(f"  POLLING_LIST_MAX_SIZE: {polling_list_max_size}")

    # Generate header (includes POLLING_LIST_MAX_SIZE)
    header_content = generate_header(categories, polling_list_max_size)

    # Write output
    print(f"\nWriting generated header to {output_file}")
    with open(output_file, 'w') as f:
        f.write(header_content)

    # -------------------------------------------------------------------------
    # Generate appliance_api_feature_lists.h from appliance_api.json
    # -------------------------------------------------------------------------
    api_json_file = repo_root / 'lib' / 'public-appliance-api-documentation' / 'appliance_api.json'
    api_output_file = repo_root / 'components' / 'geappliances_bridge' / 'appliance_api_feature_lists.h'

    if not api_json_file.exists():
        print(f"Error: Could not find {api_json_file}", file=sys.stderr)
        print("Make sure git submodules are initialized: git submodule update --init --recursive", file=sys.stderr)
        sys.exit(1)

    print(f"\nReading appliance API definitions from {api_json_file}")
    with open(api_json_file, 'r') as f:
        appliance_api_data = json.load(f)

    feature_apis = appliance_api_data.get('featureApis', {})
    common_features = appliance_api_data.get('common', {})
    valid_feature_apis = [api for api in feature_apis.values() if (api['featureType'] >> 8) <= 2]
    print(f"Found {len(feature_apis)} feature APIs ({len(valid_feature_apis)} within ERDs 0x0093-0x0095)")
    common_ver_count = sum(
        len(vd.get('features', []))
        for vd in common_features.get('versions', {}).values()
    )
    print(f"Found {common_ver_count} common features (ERD 0x0092)")

    api_header_content = generate_appliance_api_feature_lists_header(appliance_api_data)

    print(f"\nWriting generated header to {api_output_file}")
    with open(api_output_file, 'w') as f:
        f.write(api_header_content)

    print("Done!")


if __name__ == '__main__':
    main()
